@echo off
REM BabyOS Project Generator - Windows Wrapper
REM Generated by BabyOS Project Generator

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "PYTHON=python"

REM Try python3 if python doesn't work
where python >nul 2>&1
if errorlevel 1 set "PYTHON=python3"

REM Parse arguments
set "BOS_ROOT="
set "OUTPUT="
set "VENDOR="
set "CHIP="
set "PROJECT_NAME="

:parse_args
if "%~1"=="" goto :run_generator
if /i "%~1"=="--bos-root" set "BOS_ROOT=%~2" & shift & shift & goto :parse_args
if /i "%~1"=="-o" set "OUTPUT=%~2" & shift & shift & goto :parse_args
if /i "%~1"=="--vendor" set "VENDOR=%~2" & shift & shift & goto :parse_args
if /i "%~1"=="--chip" set "CHIP=%~2" & shift & shift & goto :parse_args
if /i "%~1"=="--name" set "PROJECT_NAME=%~2" & shift & shift & goto :parse_args
if /i "%~1"=="--list-vendors" set "LIST_VENDORS=1" & shift & goto :parse_args
if /i "%~1"=="--list-chips" set "LIST_CHIPS=1" & shift & goto :parse_args
shift
goto :parse_args

:run_generator
if defined LIST_VENDORS (
    %PYTHON% "%SCRIPT_DIR%babyos_project_generator.py" --list-vendors
    goto :end
)

if defined LIST_CHIPS (
    %PYTHON% "%SCRIPT_DIR%babyos_project_generator.py" --list-chips --vendor %VENDOR%
    goto :end
)

REM Build command
set "CMD=%PYTHON% "%SCRIPT_DIR%babyos_project_generator.py""
if defined BOS_ROOT set "CMD=!CMD! --bos-root "%BOS_ROOT%""
if defined OUTPUT set "CMD=!CMD! -o "%OUTPUT%""
if defined VENDOR set "CMD=!CMD! --vendor %VENDOR%"
if defined CHIP set "CMD=!CMD! --chip %CHIP%"
if defined PROJECT_NAME set "CMD=!CMD! --name %PROJECT_NAME%"

echo Running: !CMD!
!CMD!

:end
endlocal