#ifndef __B_CONFIG_H__ 
#define __B_CONFIG_H__ 


#define HW_VERSION 211212
#define FW_VERSION 80106
#define FW_NAME "BabyOS"
#define TICK_FRQ_HZ 1000
#define USER_TICK_ENABLE 1
#define VENDOR_UBUNTU 1
#define _BOS_ALGO_ENABLE 1
#define _ALGO_MD5_ENABLE 1
#define _ALGO_CRC_ENABLE 1
#define _ALGO_CRC8_ENABLE 1
#define _ALGO_CRC8_ITU_ENABLE 1
#define _ALGO_CRC8_ROHC_ENABLE 1
#define _ALGO_CRC8_MAXIM_ENABLE 1
#define _ALGO_CRC16_IBM_ENABLE 1
#define _ALGO_CRC16_MAXIM_ENABLE 1
#define _ALGO_CRC16_USB_ENABLE 1
#define _ALGO_CRC16_MODBUS_ENABLE 1
#define _ALGO_CRC16_CCITT_ENABLE 1
#define _ALGO_CRC16_CCITT_FALSE_ENABLE 1
#define _ALGO_CRC16_X25_ENABLE 1
#define _ALGO_CRC16_XMODEM_ENABLE 1
#define _ALGO_CRC16_DNP_ENABLE 1
#define _ALGO_CRC32_ENABLE 1
#define _ALGO_CRC32_MPEG2_ENABLE 1
#define PCF8574_DEFAULT_OUTPUT 0
#define MATRIX_KEYS_ROWS 4
#define MATRIX_KEYS_COLUMNS 4
#define ESP12F_CMD_TX_BUF_LEN 128
#define ESP12F_CMD_RX_BUF_LEN 1024
#define ESP12F_CMD_TIMEOUT 5000
#define ESP12F_LISTEN_PCB_NUMBER 2
#define RS485_RX_BUF_LEN 128
#define RS485_RX_IDLE_MS 50
#define _485_USE_CALLBACK 1
#define RS485_SWITCH_DELAY_US 1000
#define DISPLAY_CACHE_BUF_SIZE 8
#define _BOS_MODULES_ENABLE 1
#define _DEBUG_ENABLE 1
#define LOG_LEVEL_INFO 1
#define LOG_BUF_SIZE 256
#define _LOG_VIA_UART 1
#define LOG_UART 0
#define _BOS_SERVICES_ENABLE 1


#include "b_type.h" 

#endif 

