#ifndef __B_CONFIG_H__
#define __B_CONFIG_H__

#define HW_VERSION 211212
#define FW_VERSION 80504
#define FW_NAME "BabyOS"
#define TICK_FRQ_HZ 1000
#define VENDOR_UBUNTU 1
#define _BOS_ALGO_ENABLE 1
#define PCF8574_DEFAULT_OUTPUT 0
#define MATRIX_KEYS_ROWS 4
#define MATRIX_KEYS_COLUMNS 4
#define ESP12F_CMD_BUF_LEN 128
#define ESP12F_CMD_TIMEOUT 5000
#define RS485_RX_BUF_LEN 128
#define RS485_RX_IDLE_MS 50
#define _485_USE_CALLBACK 1
#define RS485_SWITCH_DELAY_US 1000
#define DISPLAY_CACHE_BUF_SIZE 8
#define _BOS_MODULES_ENABLE 1
#define _TCPIP_ENABLE 1
#define _TCPIP_STACK_LWIP_ENABLE 1
#define _NETIF_TRANS_USE_LWIP 1
#define NETIF_DEV_NO 1
#define NETIF_USE_DHCP 1
#define NETIF_LINK_CHECK_INTERVAL 200
#define MEM_SIZE_FOR_LWIP 10240
#define REMOTE_ADDR_LEN_MAX 128
#define CONNECT_RECVBUF_MAX 4096
#define SERVER_MAX_CONNECTIONS 2
#define _DEBUG_ENABLE 1
#define LOG_LEVEL_ALL 1
#define LOG_BUF_SIZE 256
#define _LOG_VIA_UART 1
#define LOG_UART 0
#define _BOS_SERVICES_ENABLE 1

#include "b_type.h"

#endif
