BabyOS: LCD_Exported_Functions
LCD_Exported_Functions
B_HAL » LCD
Functions
void bHalLcdWriteData (uint16_t dat)
void bHalLcdWriteCmd (uint16_t cmd)
uint16_t bHalLcdReadData ()
uint16_t bHalLcdReadCmd ()
Detailed Description
Function Documentation
bHalLcdReadCmd()
uint16_t bHalLcdReadCmd ()
Definition at line 153 of file b_hal_lcd.c.
References B_HAL_GPIO_INPUT, B_HAL_GPIO_NOPULL, B_HAL_GPIO_OUTPUT, B_HAL_PINAll, bHalGPIO_Config(), bHalGPIO_Read(), bHalGPIO_WritePin(), HAL_LCD_CS_PIN, HAL_LCD_CS_PORT, HAL_LCD_DAT_PORT, HAL_LCD_RD_PIN, HAL_LCD_RD_PORT, HAL_LCD_RS_PIN, and HAL_LCD_RS_PORT.
bHalLcdReadData()
uint16_t bHalLcdReadData ()
Definition at line 135 of file b_hal_lcd.c.
References B_HAL_GPIO_INPUT, B_HAL_GPIO_NOPULL, B_HAL_GPIO_OUTPUT, B_HAL_PINAll, bHalGPIO_Config(), bHalGPIO_Read(), bHalGPIO_WritePin(), HAL_LCD_CS_PIN, HAL_LCD_CS_PORT, HAL_LCD_DAT_PORT, HAL_LCD_RD_PIN, HAL_LCD_RD_PORT, HAL_LCD_RS_PIN, and HAL_LCD_RS_PORT.
Referenced by bILI9341_Init().
bHalLcdWriteCmd()
void bHalLcdWriteCmd (uint16_t cmd)
Definition at line 120 of file b_hal_lcd.c.
References bHalGPIO_Write(), bHalGPIO_WritePin(), HAL_LCD_CS_PIN, HAL_LCD_CS_PORT, HAL_LCD_DAT_PORT, HAL_LCD_RD_PIN, HAL_LCD_RD_PORT, HAL_LCD_RS_PIN, HAL_LCD_RS_PORT, HAL_LCD_WR_PIN, and HAL_LCD_WR_PORT.
Referenced by bILI9341_Init().
bHalLcdWriteData()
void bHalLcdWriteData (uint16_t dat)
Definition at line 105 of file b_hal_lcd.c.
References bHalGPIO_Write(), bHalGPIO_WritePin(), HAL_LCD_CS_PIN, HAL_LCD_CS_PORT, HAL_LCD_DAT_PORT, HAL_LCD_RD_PIN, HAL_LCD_RD_PORT, HAL_LCD_RS_PIN, HAL_LCD_RS_PORT, HAL_LCD_WR_PIN, and HAL_LCD_WR_PORT.
Referenced by bILI9341_Init().