BabyOS: FIFO_Exported_Functions
FIFO_Exported_Functions
BABYOS » FIFO
Functions
int bFIFO_Regist (uint8_t *pbuf, uint16_t size)
int bFIFO_Length (int no, uint16_t *plen)
int bFIFO_Flush (int no)
int bFIFO_Write (int no, uint8_t *pbuf, uint16_t size)
int bFIFO_Read (int no, uint8_t *pbuf, uint16_t size)
Detailed Description
Function Documentation
bFIFO_Flush()
int bFIFO_Flush (int no)
bFIFO_Length()
int bFIFO_Length (int no, uint16_t * plen)
Referenced by main().
bFIFO_Read()
int bFIFO_Read (int no, uint8_t * pbuf, uint16_t size)
Referenced by main().
bFIFO_Regist()
int bFIFO_Regist (uint8_t * pbuf, uint16_t size)
Referenced by main().
bFIFO_Write()
int bFIFO_Write (int no, uint8_t * pbuf, uint16_t size)
Referenced by main().