BabyOS: BOS_Private_Macros
BOS_Private_Macros
BABYOS » CORE » BOS
Functions
int bErrorCore (void)
int bBatteryCore (void)
void bXmodem128Timeout (void)
void bYmodemTimeout (void)
int bEventCore (void)
int bTX_Core (void)
void bGUI_TouchExec (void)
void bAsyntxCore (void)
Transmit data.
void bHalUartDetectIdle (void)
Detailed Description
Function Documentation
bAsyntxCore()
void bAsyntxCore (void)
Transmit data.
Return values
Result
0 OK
-1 ERR
Definition at line 135 of file b_util_asyntx.c.
Referenced by bExec().
bBatteryCore()
int bBatteryCore (void)
Referenced by bExec().
bErrorCore()
int bErrorCore (void)
Referenced by bExec().
bEventCore()
int bEventCore (void)
Referenced by bExec().
bGUI_TouchExec()
void bGUI_TouchExec (void)
Referenced by bExec().
bHalUartDetectIdle()
void bHalUartDetectIdle (void)
Definition at line 130 of file b_hal_uart.c.
References B_HAL_UART_NUMBER, and bUtilGetTick().
Referenced by bExec().
bTX_Core()
int bTX_Core (void)
bXmodem128Timeout()
void bXmodem128Timeout (void)
Referenced by bExec().
bYmodemTimeout()
void bYmodemTimeout (void)
Referenced by bExec().