BabyOS: BATTERY_Exported_Functions
BATTERY_Exported_Functions
BABYOS » MODULES » BATTERY
Functions
__weak int bBatteryGetmV (uint16_t *pmV)
Get Voltage (mV)
int bBatteryCore ()
Read V and compare with bLowThreshold _BATTERY_THRESHOLD.
uint8_t bBatGetStatus ()
Get Status.
uint16_t bBatGetVoltageValue ()
Get Voltage.
Detailed Description
Function Documentation
bBatGetStatus()
uint8_t bBatGetStatus ()
Get Status.
Return values
Battery Status
bBAT_STA_NORMAL
bBAT_STA_LOW
Definition at line 180 of file b_mod_battery.c.
bBatGetVoltageValue()
uint16_t bBatGetVoltageValue ()
Get Voltage.
Return values
Battery voltage value (mv)
Definition at line 190 of file b_mod_battery.c.
bBatteryCore()
int bBatteryCore (void)
Read V and compare with bLowThreshold _BATTERY_THRESHOLD.
Return values
Result
0 OK
-1 ERR
Definition at line 138 of file b_mod_battery.c.
References bBatteryGetmV().
Referenced by bExec().
bBatteryGetmV()
__weak int bBatteryGetmV (uint16_t * pmV)
Get Voltage (mV)
Parameters
pmV Pointer to value
Return values
Result
0 OK
-1 ERR
Definition at line 121 of file b_mod_battery.c.
References NULL.
Referenced by bBatteryCore().