BabyOS: DELAY_Exported_Functions
DELAY_Exported_Functions
B_UTILS » DELAY
Functions
void bUtilDelayMS (uint32_t xms)
void bUtilDelayUS (uint32_t xus)
uint32_t bUtilGetTick ()
Detailed Description
Function Documentation
bUtilDelayMS()
void bUtilDelayMS (uint32_t xms)
Definition at line 106 of file b_util_delay.c.
References _TICK_FRQ_HZ, and bSysTick.
Referenced by bILI9341_Init().
bUtilDelayUS()
void bUtilDelayUS (uint32_t xus)
Definition at line 117 of file b_util_delay.c.
bUtilGetTick()
uint32_t bUtilGetTick ()
Definition at line 125 of file b_util_delay.c.
References bSysTick.
Referenced by bExec(), and bHalUartDetectIdle().