BabyOS: ILI9341_Exported_Functions
ILI9341_Exported_Functions
BABYOS » B_DRIVER » ILI9341
Functions
int bILI9341_Init (void)
Detailed Description
Function Documentation
bILI9341_Init()
int bILI9341_Init (void)
Definition at line 155 of file b_drv_ili9341.c.
References bHalLcdReadData(), bHalLcdWriteCmd(), bHalLcdWriteData(), bILI9341_Driver, bUtilDelayMS(), bDriverInterface::close, bDriverInterface::ctl, NULL, bDriverInterface::open, bDriverInterface::read, and bDriverInterface::write.