BabyOS: BOS_Exported_Functions
BOS_Exported_Functions
BABYOS » BOS
Functions
int bInit ()
Init.
int bExec ()
Call this function inside the while(1)
Detailed Description
Function Documentation
bExec()
int bExec ()
Call this function inside the while(1)
Return values
Result
0 OK
-1 ERR
Definition at line 141 of file b_os.c.
References _BATTERY_D_CYCLE, _TICK_FRQ_HZ, bAsyntxCore(), bBatteryCore(), bErrorCore(), bEventCore(), bGUI_TouchExec(), bHalGetTick(), bXmodem128Timeout(), bYmodemTimeout(), FLEX_BTN_SCAN_FREQ_HZ, and MS2TICKS.
bInit()
int bInit ()
Init.
Return values
Result
0 OK
-1 ERR
Definition at line 120 of file b_os.c.
References b_log, bDEV_MAX_NUM, bDeviceInit(), and bHalInit().