BabyOS: GPIO_Exported_Functions
GPIO_Exported_Functions
B_HAL » GPIO
Functions
void bHalGPIO_Config (uint8_t port, uint8_t pin, uint8_t mode, uint8_t pull)
Configure GPIO, Dont Initialize GPIO with this function. It's only used to switch in/out mode.
void bHalGPIO_WritePin (uint8_t port, uint8_t pin, uint8_t s)
uint8_t bHalGPIO_ReadPin (uint8_t port, uint8_t pin)
void bHalGPIO_Write (uint8_t port, uint16_t dat)
uint16_t bHalGPIO_Read (uint8_t port)
void bHalGPIO_RegEXTICallback (uint8_t pin, pEXTI_Callback cb)
void bHalGPIO_EXTI_Callback (uint8_t pin)
EXTI line detection callbacks.
Detailed Description
Function Documentation
bHalGPIO_Config()
void bHalGPIO_Config (uint8_t port, uint8_t pin, uint8_t mode, uint8_t pull)
Configure GPIO, Dont Initialize GPIO with this function. It's only used to switch in/out mode.
Parameters
port the port number
pin the pin number
mode gpio mode
B_HAL_GPIO_OUTPUT output mode
B_HAL_GPIO_INPUT input mode
pull gpio pull
B_HAL_GPIO_NOPULL no-pull mode
B_HAL_GPIO_PULLUP pull-up mode
B_HAL_GPIO_PULLDOWN pull-down mode
Definition at line 120 of file b_hal_gpio.c.
References B_HAL_GPIO_NOPULL, B_HAL_GPIO_OUTPUT, and B_HAL_GPIO_PULLUP.
Referenced by bHalLcdReadCmd(), and bHalLcdReadData().
bHalGPIO_EXTI_Callback()
void bHalGPIO_EXTI_Callback (uint8_t pin)
EXTI line detection callbacks.
Parameters
pin Specifies the pins connected EXTI line bHalGPIOPin_t
Definition at line 172 of file b_hal_gpio.c.
References B_HAL_PINAll.
bHalGPIO_Read()
uint16_t bHalGPIO_Read (uint8_t port)
Definition at line 151 of file b_hal_gpio.c.
Referenced by bHalLcdReadCmd(), and bHalLcdReadData().
bHalGPIO_ReadPin()
uint8_t bHalGPIO_ReadPin (uint8_t port, uint8_t pin)
Definition at line 137 of file b_hal_gpio.c.
bHalGPIO_RegEXTICallback()
void bHalGPIO_RegEXTICallback (uint8_t pin, pEXTI_Callback cb)
Definition at line 158 of file b_hal_gpio.c.
References B_HAL_PINAll.
bHalGPIO_Write()
void bHalGPIO_Write (uint8_t port, uint16_t dat)
Definition at line 146 of file b_hal_gpio.c.
Referenced by bHalLcdWriteCmd(), and bHalLcdWriteData().
bHalGPIO_WritePin()
void bHalGPIO_WritePin (uint8_t port, uint8_t pin, uint8_t s)
Definition at line 131 of file b_hal_gpio.c.
Referenced by bHalLcdReadCmd(), bHalLcdReadData(), bHalLcdWriteCmd(), and bHalLcdWriteData().