BabyOS: bDriverInterface Struct Reference
bDriverInterface Struct Reference
BABYOS » DEVICE » DEVICE_Exported_TypesDefinitions
#include <b_device.h>
Data Fields
int(* init)(struct bDriverInterface *)
int(* open)(void)
int(* close)(void)
int(* ctl)(uint8_t cmd, void *param)
int(* write)(uint32_t addr, uint8_t *pbuf, uint16_t len)
int(* read)(uint32_t addr, uint8_t *pbuf, uint16_t len)
void * _private
Detailed Description
Definition at line 83 of file b_device.h.
Field Documentation
_private
void* _private
Definition at line 91 of file b_device.h.
Referenced by bW25X_Init(), S_UartRXStart(), S_UartRxTimerHandler(), S_UartTxTimerHandler(), and SUART_Init().
close
int(* close) (void)
Definition at line 87 of file b_device.h.
Referenced by SUART_Init().
ctl
int(* ctl) (uint8_t cmd, void *param)
Definition at line 88 of file b_device.h.
Referenced by SUART_Init().
init
int(* init) (struct bDriverInterface *)
Definition at line 85 of file b_device.h.
open
int(* open) (void)
Definition at line 86 of file b_device.h.
Referenced by SUART_Init().
read
int(* read) (uint32_t addr, uint8_t *pbuf, uint16_t len)
Definition at line 90 of file b_device.h.
Referenced by SUART_Init().
write
int(* write) (uint32_t addr, uint8_t *pbuf, uint16_t len)
Definition at line 89 of file b_device.h.
The documentation for this struct was generated from the following file:
b_device.h